version: "3.3"

services:
  # database
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: 'postgres-container'
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d oms"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
