// Code generated by MockGen. DO NOT EDIT.
// Source: ./mocks/order.go
//
// Generated by this command:
//
//	mockgen -source ./mocks/order.go -destination=./mocks/mock_order.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	dto "homework/internal/dto"
	model "homework/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockorderStorage is a mock of orderStorage interface.
type MockorderStorage struct {
	ctrl     *gomock.Controller
	recorder *MockorderStorageMockRecorder
}

// MockorderStorageMockRecorder is the mock recorder for MockorderStorage.
type MockorderStorageMockRecorder struct {
	mock *MockorderStorage
}

// NewMockorderStorage creates a new mock instance.
func NewMockorderStorage(ctrl *gomock.Controller) *MockorderStorage {
	mock := &MockorderStorage{ctrl: ctrl}
	mock.recorder = &MockorderStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderStorage) EXPECT() *MockorderStorageMockRecorder {
	return m.recorder
}

// AddOrder mocks base method.
func (m *MockorderStorage) AddOrder(ctx context.Context, order model.Order, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrder", ctx, order, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOrder indicates an expected call of AddOrder.
func (mr *MockorderStorageMockRecorder) AddOrder(ctx, order, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrder", reflect.TypeOf((*MockorderStorage)(nil).AddOrder), ctx, order, hash)
}

// DeleteOrder mocks base method.
func (m *MockorderStorage) DeleteOrder(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrder", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrder indicates an expected call of DeleteOrder.
func (mr *MockorderStorageMockRecorder) DeleteOrder(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrder", reflect.TypeOf((*MockorderStorage)(nil).DeleteOrder), ctx, id)
}

// GetOrderById mocks base method.
func (m *MockorderStorage) GetOrderById(ctx context.Context, id string) (model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderById", ctx, id)
	ret0, _ := ret[0].(model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderById indicates an expected call of GetOrderById.
func (mr *MockorderStorageMockRecorder) GetOrderById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderById", reflect.TypeOf((*MockorderStorage)(nil).GetOrderById), ctx, id)
}

// ListOrdersByIds mocks base method.
func (m *MockorderStorage) ListOrdersByIds(ctx context.Context, ids []string, status model.Status) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrdersByIds", ctx, ids, status)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrdersByIds indicates an expected call of ListOrdersByIds.
func (mr *MockorderStorageMockRecorder) ListOrdersByIds(ctx, ids, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrdersByIds", reflect.TypeOf((*MockorderStorage)(nil).ListOrdersByIds), ctx, ids, status)
}

// ListUserOrders mocks base method.
func (m *MockorderStorage) ListUserOrders(ctx context.Context, userId string, count uint, status model.Status) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserOrders", ctx, userId, count, status)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserOrders indicates an expected call of ListUserOrders.
func (mr *MockorderStorageMockRecorder) ListUserOrders(ctx, userId, count, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserOrders", reflect.TypeOf((*MockorderStorage)(nil).ListUserOrders), ctx, userId, count, status)
}

// RefundedOrders mocks base method.
func (m *MockorderStorage) RefundedOrders(ctx context.Context, get dto.PageParam) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefundedOrders", ctx, get)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefundedOrders indicates an expected call of RefundedOrders.
func (mr *MockorderStorageMockRecorder) RefundedOrders(ctx, get any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefundedOrders", reflect.TypeOf((*MockorderStorage)(nil).RefundedOrders), ctx, get)
}

// UpdateStatus mocks base method.
func (m *MockorderStorage) UpdateStatus(ctx context.Context, ids dto.IdsWithHashes, status model.Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, ids, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockorderStorageMockRecorder) UpdateStatus(ctx, ids, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockorderStorage)(nil).UpdateStatus), ctx, ids, status)
}
